figure;
hold on;
grid on;
title('Pierwszy matlab');
xlabel('t');
ylabel('x_s');
x = [-10:1:10];
a = [-2:.5:2];
colors = ['r- ';'b--';'g: ';'y-.'];
description = ['pomiar 1';'pomiar 2';'pomiar 3';'pomiar 4'];
for i=1:size(a,2);
    color_line = mod(i,size(colors,1))+1;
    plot(x,a(i)*x.*x,colors(color_line,:));
end;
legend(description);